// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmprestimoLivros.API.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("cliCpf")]
        [StringLength(14)]
        public string CliCpf { get; set; }
        [Column("cliNome")]
        [StringLength(100)]
        public string CliNome { get; set; }
        [Column("cliEndereco")]
        [StringLength(100)]
        public string CliEndereco { get; set; }
        [Column("cliCidade")]
        [StringLength(100)]
        public string CliCidade { get; set; }
        [Column("cliBairro")]
        [StringLength(100)]
        public string CliBairro { get; set; }
        [Column("cliNumero")]
        [StringLength(100)]
        public string CliNumero { get; set; }
        [Column("cliTelefoneCelular")]
        [StringLength(100)]
        public string CliTelefoneCelular { get; set; }
        [Column("cliTelefoneFixo")]
        [StringLength(100)]
        public string CliTelefoneFixo { get; set; }
        
        [InverseProperty("LceIdClienteNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}