// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EmprestimoLivros.API.Models
{
    public partial class EmprestimoLivrosContext : DbContext
    {
        public EmprestimoLivrosContext()
        {
        }

        public EmprestimoLivrosContext(DbContextOptions<EmprestimoLivrosContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Livro> Livro { get; set; }
        public virtual DbSet<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CliBairro).IsUnicode(false);

                entity.Property(e => e.CliCidade).IsUnicode(false);

                entity.Property(e => e.CliCpf).IsUnicode(false);

                entity.Property(e => e.CliEndereco).IsUnicode(false);

                entity.Property(e => e.CliNome).IsUnicode(false);

                entity.Property(e => e.CliNumero).IsUnicode(false);

                entity.Property(e => e.CliTelefoneCelular).IsUnicode(false);

                entity.Property(e => e.CliTelefoneFixo).IsUnicode(false);
            });

            modelBuilder.Entity<Livro>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.LivroAutor).IsUnicode(false);

                entity.Property(e => e.LivroEdicao).IsUnicode(false);

                entity.Property(e => e.LivroEditora).IsUnicode(false);

                entity.Property(e => e.LivroNome).IsUnicode(false);
            });

            modelBuilder.Entity<LivroClienteEmprestimo>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.HasOne(d => d.LceIdClienteNavigation)
                    .WithMany(p => p.LivroClienteEmprestimo)
                    .HasForeignKey(d => d.LceIdCliente)
                    .HasConstraintName("fk_Cliente");

                entity.HasOne(d => d.LceIdLivroNavigation)
                    .WithMany(p => p.LivroClienteEmprestimo)
                    .HasForeignKey(d => d.LceIdLivro)
                    .HasConstraintName("fk_Livro");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}